x-app-common:
  &app-common
  env_file:
    - .env
  build:
    context: .
    dockerfile: ${DOCKERFILE}
    args:
      - DEV_IMAGE=${DEV_IMAGE}
      - WORK_DIR=${WORK_DIR}
      - REQUIREMENTS_FILE=${REQUIREMENTS_FILE}
      - USER_UID=${USER_UID:-0}
      - USER_GID=${USER_GID:-0}
  # stdin_open: mantém o fluxo de entrada padrão (stdin) aberto para o contêiner, permitindo que
  # o usuário envie comandos interativamente para o contêiner,
  stdin_open: true
  # tty:  aloca um terminal virtual (TTY) para o contêiner. Um TTY é uma interface de terminal
  # usada para interagir com o contêiner de forma mais natural, como em um terminal
  #de sistema operacional.
  tty: true
  ulimits:
    memlock: -1
    nofile:
      soft: 65536
      hard: 65536
  environment:
    - WORK_DIR=${WORK_DIR}
    - USER_UID=${USER_UID}
    - USER_GID=${USER_GID}
  volumes:
    - .:${WORK_DIR:-/opt/app}
  networks:
    - net

services:
  django:

  redis:

  db:

  pgadmin:
