ARG DEV_IMAGE=python-nodejs-base:latest
FROM ${DEV_IMAGE} AS app-dev

ARG WORK_DIR
ARG REQUIREMENTS_FILE
ARG USER_NAME

# Persistir as variáveis como ambiente no runtime
ENV WORK_DIR=${WORK_DIR}
ENV REQUIREMENTS_FILE=${REQUIREMENTS_FILE}
ENV USER_NAME=${USER_NAME}

# Defina o usuário padrão para o container
USER $USER_NAME

# Definir o diretório de trabalho usando o argumento passado
# diretório padrão onde o CMD será executado
WORKDIR $WORK_DIR

# Adicionar os arquivos da aplicação
COPY . $WORK_DIR

# Install requirements
# --mount=type=cache,target=/root/.cache/pip é uma opção avançada do Docker,
# introduzida no BuildKit (um recurso mais recente do Docker para melhorar a
# eficiência da construção de imagens). Ela cria um cache temporário durante
# o processo de construção.
RUN --mount=type=cache,target=/root/.cache/pip pip install -r ${REQUIREMENTS_FILE}

CMD ["/bin/sh", "-c", "echo 'Starting dev container'; sleep infinity"]