# terceiro estágio: começa da imagem base anterior e adiciona Node.js
ARG PYTHON_NODEJS_BASE_IMAGE=python-base-user:latest
FROM ${PYTHON_NODEJS_BASE_IMAGE} AS python-nodejs-base

# Instalar Node.js e Yarn de forma mais simples
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs && \
    corepack enable yarn && \
    && apt-get -y autoremove && apt-get clean \
    && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/*

# docker build -f /home/jailton/workstation/docker_service/dockerfiles/Dockerfile-base-python-nodejs  -t python-nodejs-base:latest .