ARG POSTGRES_IMAGE=postgres:16.3
FROM ${POSTGRES_IMAGE}

RUN apt-get update && apt-get install -yqq --no-install-recommends --fix-missing \
      procps pv pigz tar gzip unzip file postgis net-tools iptables \
    && apt-get -y autoremove && apt-get clean \
    && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* \

# -y:
# Responde automaticamente "sim" a todas as perguntas feitas durante a instalação \

# -qq:
# Faz o processo de instalação ser extremamente silencioso,
# mostrando apenas mensagens de erro ou informações críticas.

# --no-install-recommends:
# Não instalar pacotes recomendados.
# O APT só instala as dependências obrigatórias, resultando em uma instalação mais enxuta

# --fix-missing:
# Tenta corrigir pacotes ausentes ou quebrados durante a instalação

# apt-get -y autoremove:
# Remove pacotes que foram instalados automaticamente como dependências, mas que não são mais necessários

# apt-get clean:
# Limpa o cache de pacotes baixados que ficam armazenados no diretório /var/cache/apt/archives.

# rm -rf /var/cache/apt/*:
# Remove diretamente todo o conteúdo do diretório /var/cache/apt/,
# que contém caches e pacotes temporários usados durante a instalação

# rm -rf /var/lib/apt/lists:  \
# Remove os arquivos de lista de pacotes baixados pelo comando apt-get update.
# Esses arquivos listam os pacotes disponíveis e as suas versões, e são usados durante a instalação para verificar as dependências e baixar os pacotes adequados.