ARG PYTHON_BASE_IMAGE=python:3.12-slim-bullseye
FROM ${PYTHON_BASE_IMAGE} AS python-base

# Env variables
# Desabilita o buffering de saída padrão do Python.
# Garante que a saída do Python (como impressões no console) seja imediatamente enviada
# para o terminal ou logs, sem ficar retida no buffer.
# Isso é particularmente útil em ambientes de contêiner onde é importante ver os logs em tempo real.
ENV PYTHONUNBUFFERED 1

# Impede o Python de gerar arquivos .pyc, que são os bytecodes compilados do Python, em diretórios de origem.
# Isso ajuda a manter os diretórios de código mais limpos e evita a criação de arquivos desnecessários
# em um ambiente de contêiner, onde o armazenamento em disco pode ser mais limitado
# e a limpeza de arquivos indesejados pode ser preferível.
ENV PYTHONDONTWRITEBYTECODE 1

ENV POETRY_HOME=/usr/local
ENV DEBIAN_FRONTEND noninteractive
ENV LANG pt_BR.UTF-8
ENV LANGUAGE pt_BR:pt
ENV LC_ALL pt_BR.UTF-8
ENV TZ="America/Fortaleza"
RUN export LANG=C.UTF-8

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean \
    && sed -i -e's/ main/ main contrib non-free/g' /etc/apt/sources.list

RUN apt-get update && apt-get install -yqq --fix-missing --no-install-recommends \
        wget gnupg2 unzip \
        pip python3-setuptools python3-wheel \
        locales vim openssh-server git build-essential \
        nginx cron libldap2-dev libsasl2-dev libpq-dev ghostscript \
        libjpeg-dev libfreetype6-dev zlib1g-dev \
        freetds-dev libxmlsec1-dev libxml2-dev libxslt1-dev \
        libblas-dev liblapack-dev libatlas-base-dev gfortran \
        libglu1-mesa libcairo2 libcairo2-dev libcups2 libdbus-glib-1-2 libxinerama1 libsm6 \
        tmpreaper libgdk-pixbuf2.0-0 libffi-dev shared-mime-info \
        python3-cffi libpango-1.0-0 libpangocairo-1.0-0 \
        ntpdate swig openssl libssl-dev libxrender-dev  \
        git-core libx11-dev libxext-dev ttf-mscorefonts-installer libfontconfig1-dev fontconfig curl qpdf \
    && apt-get -y autoremove && apt-get clean \
    && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/*


RUN  pip install -U pip pipenv uv && \
  curl -sSL https://install.python-poetry.org | python -

RUN echo "pt_BR.UTF-8 UTF-8" >> /etc/locale.gen
RUN locale-gen pt_BR.UTF-8
RUN ln -s /usr/bin/gs /usr/local/bin/gs
RUN --mount=type=cache,target=/root/.cache/pip pip install nltk==3.8
RUN python -c "import nltk; nltk.download('punkt', download_dir='/var/www/nltk_data'); nltk.download('stopwords', download_dir='/var/www/nltk_data'); "

ADD https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz /root/wkhtmltox.tar.xz
RUN tar -xvf /root/wkhtmltox.tar.xz -C /root && mv /root/wkhtmltox/bin/wkhtmlto* /usr/bin && fc-cache -f -v


# Google Chrome Stable: É o navegador completo, a versão estável do Google Chrome,
# utilizada por usuários para navegação e, em automação, para realizar as ações simuladas
# nos testes (como abrir páginas, clicar em links etc.).

# ChromeDriver: É um binário que atua como intermediário entre ferramentas de automação (como Selenium)
# e o navegador Chrome. Ele traduz os comandos de automação em ações reais no navegador.

# Adição da chave GPG e do repositório do Google Chrome Stable
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list


# Instala a versão estável do Google Chrome Stable (navegador)
RUN apt-get update && apt-get install -yqq --fix-missing --no-install-recommends \
    google-chrome-stable \
    && apt-get -y autoremove && apt-get clean \
    && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/*

# Baixa o chromedriver à versão do navegador Chrome e instala do ChromeDriver
RUN wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip &&\
      unzip chromedriver_linux64.zip &&\
      cp chromedriver /usr/local/bin/chromedriver \

# docker build -t pyton-base:latest -f /home/jailton/workstation/sdocker/dockerfiles/Dockerfile-base-python  .